remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [East Meets West - Investigating Power Outage Patterns across US States]
description: [This study investigates whether the number of power outages per 100,000 people differs significantly between states in the East and West regions of the United States.]